"""Render authoritative generated artifacts in memory and check for drift.

Usage:
  python tools/zyr.py build --check
"""

from __future__ import annotations

import hashlib
import os
import re
import stat
import tempfile
from collections import defaultdict
from pathlib import Path
from typing import Any, Callable

from .manifest import (
    ROOT,
    RepositoryContractError,
    load_yaml_mapping,
    parse_front_matter,
    resolve_repo_path,
    validate_repository_contract,
)
from .resource_profile_v1 import engine_addendum

MODULE_RE = re.compile(r"^\d{2}_.+\.md$")
SKILL_ID_RE = re.compile(r"S(\d+)")
SKILL_MAP_ORDER = [
    "research_core",
    "experiments",
    "reproducibility",
    "paper_ops",
    "research_writing_integrated",
    "figure_design_integrated",
    "s340_integrated",
    "reproducibility_integrated",
    "composite",
]
Renderer = Callable[[Path, dict[str, Any], list[dict[str, Any]]], str]


def _module_files(root: Path, relative_dir: str) -> list[Path]:
    directory = resolve_repo_path(root, relative_dir, "module directory")
    modules = sorted(
        path
        for path in directory.iterdir()
        if path.is_file()
        and MODULE_RE.fullmatch(path.name)
        and not path.name.startswith("99_")
    )
    if not modules:
        raise RepositoryContractError(f"No source modules found in {relative_dir}")
    return modules


def render_writing_engine(
    root: Path, manifest: dict[str, Any], _entries: list[dict[str, Any]]
) -> str:
    """Render the authoritative writing master."""
    version = str(manifest["version"])
    parts = [
        f"# MASTER v{version} (Writing Engine)\n",
        "> This file is generated by `python tools/zyr.py build`.\n",
        (
            "> **Component lineage:** the preserved writing modules originate from the "
            "v1.3.2-compatible prompt line; the active suite and this entrypoint are "
            f"v{version}.\n"
        ),
        (
            f"> **v{version} binding addendum:** Any visible writing task in ZYR must call "
            f"`writing_engine`. In the v{version} stack, `writing_engine` is backed by "
            "`ext/src/rpws/` (Research-Paper-Writing-Skills) and must use the integrated "
            "wrappers `S601`/`S602`/`S603`/`S604` together with `S640` as the global "
            "writing and logic gate.\n"
        ),
        (
            "> **Execution rules:** `boot/11_COMPLETION_FIRST_ANTI_SHORTCUT_v1.5.md` "
            "applies after lock activation.\n\n---\n"
        ),
    ]
    parts.insert(1, engine_addendum("writing_engine"))
    for path in _module_files(root, "skills/writing_engine/modules"):
        parts.append(path.read_text(encoding="utf-8").rstrip())
        parts.append("\n\n---\n")
    return "\n".join(parts).rstrip() + "\n"


def render_coding_engine(
    root: Path, manifest: dict[str, Any], _entries: list[dict[str, Any]]
) -> str:
    version = str(manifest["version"])
    parts = [f"# MASTER v{version} (Coding Engine)\n"]
    parts.append("> This file is generated by `python tools/zyr.py build`.\n")
    parts.append(
        "> **Component lineage:** the preserved coding modules remain "
        f"v1.3.2-compatible; the active suite and this entrypoint are v{version}.\n"
    )
    parts.append(
        "> **Normative rules:** `skills/reproducibility/S430_debug_vibe_core.md` + "
        "`boot/10_LOCKED_SCOPE_GUARD_v1.3.md` + "
        "`boot/11_COMPLETION_FIRST_ANTI_SHORTCUT_v1.5.md`.\n\n---\n"
    )
    parts.insert(1, engine_addendum("coding_engine"))
    for path in _module_files(root, "skills/coding_engine/modules"):
        parts.append(path.read_text(encoding="utf-8").rstrip())
        parts.append("\n\n---\n")
    return "\n".join(parts).rstrip() + "\n"


def render_proof_engine(
    root: Path, manifest: dict[str, Any], _entries: list[dict[str, Any]]
) -> str:
    version = str(manifest["version"])
    parts = [
        "# MASTER v1.5 (Proof Engine)\n",
        (
            f"> **v{version} binding addendum:** Any research-idea construction, method design, "
            "theoretical framing, contribution definition, paper-storyline construction, "
            "theorem/proof sketch, derivation, or claim-evidence task must call "
            f"`proof_engine` before prose polishing. In the v{version} stack, `proof_engine` "
            "is the reasoning gate that stabilizes the idea-method-evidence chain before "
            "`writing_engine` turns it into polished text.\n"
        ),
        "> This file is generated by `python tools/zyr.py build`.\n",
        (
            "> **Normative rules:** `boot/04_MODE_LOCK_FORMAT_v1.3.2.md` + "
            "`boot/11_COMPLETION_FIRST_ANTI_SHORTCUT_v1.5.md` + "
            "`boot/13_SCIENTIFIC_ASSISTANT_OUTPUT_DISCIPLINE_v1.5.md` + "
            "`skills/research_core/S240_pessimistic_proof_verification.md` + "
            "`skills/research_core/S241_progressive_proof_verification.md`.\n\n---\n"
        ),
    ]
    parts.insert(1, engine_addendum("proof_engine"))
    for path in _module_files(root, "skills/proof_engine/modules"):
        parts.append(path.read_text(encoding="utf-8").rstrip())
        parts.append("\n\n---\n")
    return "\n".join(parts).rstrip() + "\n"


def _canonical_atomic_entries(
    root: Path, entries: list[dict[str, Any]]
) -> list[tuple[dict[str, Any], dict[str, Any]]]:
    resolved: list[tuple[dict[str, Any], dict[str, Any]]] = []
    atomics = sorted(
        (item for item in entries if str(item["category"]) != "composite"),
        key=lambda item: str(item["path"]),
    )
    for item in atomics:
        path = resolve_repo_path(root, str(item["path"]), f"active skill {item['id']}")
        resolved.append((item, parse_front_matter(path)))
    return resolved


def render_index(
    root: Path, manifest: dict[str, Any], entries: list[dict[str, Any]]
) -> str:
    buckets: dict[str, list[tuple[str, str, str]]] = {}
    for item, front_matter in _canonical_atomic_entries(root, entries):
        category = str(front_matter.get("category", "uncategorized"))
        sid = str(front_matter.get("id", item["id"]))
        name = str(front_matter.get("name", item["name"]))
        buckets.setdefault(category, []).append((sid, name, str(item["path"])))
    for item in entries:
        if str(item["category"]) == "composite":
            buckets.setdefault("composite", []).append(
                (str(item["id"]), str(item["name"]), str(item["path"]))
            )

    lines = [
        f"# Index ({manifest['version']})\n",
        "This file is generated by `python tools/zyr.py build`.\n",
    ]
    for category in sorted(buckets):
        lines.append(f"## {category}\n")
        for sid, name, relative in buckets[category]:
            lines.append(f"- **{sid}** `{name}` — {relative}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _id_number(sid: str) -> int:
    match = SKILL_ID_RE.match(sid)
    return int(match.group(1)) if match else 10**9


def render_skill_map(
    root: Path, manifest: dict[str, Any], entries: list[dict[str, Any]]
) -> str:
    buckets: defaultdict[str, list[tuple[int, str, str, str, str]]] = defaultdict(list)
    for item in entries:
        if str(item["category"]) == "composite":
            outputs = item.get("outputs", []) or []
            trigger = "generated composite"
            if outputs:
                trigger += f"; outputs: {', '.join(str(value) for value in outputs[:3])}"
            buckets["composite"].append(
                (10**8, str(item["id"]), str(item["name"]), str(item["path"]), trigger)
            )
            continue

        path = resolve_repo_path(root, str(item["path"]), f"active skill {item['id']}")
        front_matter = parse_front_matter(path)
        category = str(front_matter.get("category", "uncategorized"))
        sid = str(front_matter.get("id", item["id"]))
        name = str(front_matter.get("name", item["name"]))
        triggers = front_matter.get("triggers", []) or []
        if isinstance(triggers, str):
            triggers = [triggers]
        trigger_text = ", ".join(str(value) for value in triggers[:6])
        if len(triggers) > 6:
            trigger_text += ", ..."
        buckets[category].append(
            (_id_number(sid), sid, name, str(item["path"]), trigger_text)
        )

    for values in buckets.values():
        values.sort()
    lines = [
        f"# Skill Map (v{manifest['version']})",
        "",
        "This file is generated by `python tools/zyr.py build`.",
        "",
        "This is a human-readable map from intents → primary skills.",
        "",
        "Prefer using **one** primary skill per task.",
        "",
    ]
    for category in SKILL_MAP_ORDER:
        lines.extend((f"## {category}", ""))
        for _, sid, name, relative, trigger in buckets.get(category, []):
            lines.append(f"- **{sid}** `{name}` — {relative}")
            lines.append(f"  - triggers: {trigger}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


RENDERERS: dict[str, Renderer] = {
    "tools.zyr_lib.build:render_writing_engine": render_writing_engine,
    "tools.zyr_lib.build:render_coding_engine": render_coding_engine,
    "tools.zyr_lib.build:render_proof_engine": render_proof_engine,
    "tools.zyr_lib.build:render_index": render_index,
    "tools.zyr_lib.build:render_skill_map": render_skill_map,
}


def _load_generated_entries(root: Path) -> list[dict[str, Any]]:
    data = load_yaml_mapping(root / "manifests" / "generated_files.yaml")
    if data.get("schema_version") != 1:
        raise RepositoryContractError("generated_files.yaml schema_version must be 1")
    raw_entries = data.get("generated_files")
    if not isinstance(raw_entries, list) or not raw_entries:
        raise RepositoryContractError(
            "generated_files.yaml must contain a non-empty `generated_files` list"
        )
    entries: list[dict[str, Any]] = []
    seen_paths: set[str] = set()
    seen_builders: set[str] = set()
    errors: list[str] = []
    for index, raw in enumerate(raw_entries):
        if not isinstance(raw, dict):
            errors.append(f"generated file entry {index} is not a mapping")
            continue
        relative = str(raw.get("path", "")).strip()
        builder = str(raw.get("builder", "")).strip()
        inputs = raw.get("inputs")
        if not relative or builder not in RENDERERS or not isinstance(inputs, list) or not inputs:
            errors.append(
                f"generated file entry {index} requires path/known builder/non-empty inputs"
            )
            continue
        if relative in seen_paths:
            errors.append(f"Generated path has multiple builders: {relative}")
        else:
            seen_paths.add(relative)
        if builder in seen_builders:
            errors.append(f"Builder is assigned to multiple generated paths: {builder}")
        else:
            seen_builders.add(builder)
        for raw_input in inputs:
            input_relative = str(raw_input).strip()
            try:
                input_path = resolve_repo_path(root, input_relative, f"input for {relative}")
            except RepositoryContractError as exc:
                errors.append(str(exc))
                continue
            if not input_path.exists():
                errors.append(f"Missing generated input for {relative}: {input_relative}")
        entries.append(dict(raw))
    if errors:
        raise RepositoryContractError("\n".join(errors))
    return entries


def check_generated(root: Path = ROOT) -> list[str]:
    """Return deterministic drift errors without writing to the repository."""
    manifest, active_entries, _ = validate_repository_contract(root)
    generated_entries = _load_generated_entries(root)
    errors: list[str] = []
    for item in generated_entries:
        relative = str(item["path"])
        output = resolve_repo_path(root, relative, f"generated output {relative}")
        if not output.is_file():
            errors.append(f"Missing generated output: {relative}")
            continue
        expected = RENDERERS[str(item["builder"])](root, manifest, active_entries).encode(
            "utf-8"
        )
        actual = output.read_bytes()
        if actual != expected:
            expected_hash = hashlib.sha256(expected).hexdigest()
            actual_hash = hashlib.sha256(actual).hexdigest()
            errors.append(
                f"Generated drift at {relative}: expected sha256={expected_hash}, "
                f"actual sha256={actual_hash}"
            )
    return errors


def _render_all(root: Path) -> list[tuple[Path, str, bytes]]:
    generated_entries = _load_generated_entries(root)
    generated_paths = {str(item["path"]) for item in generated_entries}
    manifest, active_entries, _ = validate_repository_contract(
        root,
        allowed_missing_active_paths=generated_paths,
    )
    rendered: list[tuple[Path, str, bytes]] = []
    for item in generated_entries:
        relative = str(item["path"])
        nominal_output = root / relative
        if nominal_output.is_symlink():
            raise RepositoryContractError(
                f"Refusing generated output symlink: {relative}"
            )
        output = resolve_repo_path(root, relative, f"generated output {relative}")
        expected = RENDERERS[str(item["builder"])](root, manifest, active_entries).encode(
            "utf-8"
        )
        rendered.append((output, relative, expected))
    return rendered


def _replace_atomic(path: Path, data: bytes) -> None:
    if not path.parent.is_dir():
        raise OSError(f"Generated output parent is missing: {path.parent}")
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent)
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def run_build(root: Path = ROOT) -> int:
    """Write only allowlisted generated outputs via same-directory atomic replace."""
    try:
        rendered = _render_all(root)
    except RepositoryContractError as exc:
        print(f"Build failed:\n- {str(exc).replace(chr(10), chr(10) + '- ')}")
        return 1

    changed: list[str] = []
    try:
        for output, relative, expected in rendered:
            if output.is_file() and output.read_bytes() == expected:
                continue
            _replace_atomic(output, expected)
            changed.append(relative)
    except OSError as exc:
        print(f"Build failed while writing allowlisted output: {exc}")
        return 1

    errors = check_generated(root)
    if errors:
        print("Build failed post-write verification:")
        for error in errors:
            print(f"- {error}")
        return 1
    print(
        f"Build passed: generated_files={len(rendered)} changed={len(changed)} "
        "write_mode=allowlisted_atomic_replace"
    )
    for relative in changed:
        print(f"- {relative}")
    return 0


def run_build_check(root: Path = ROOT) -> int:
    """Print a build-check result and return a process-compatible status."""
    try:
        errors = check_generated(root)
    except RepositoryContractError as exc:
        print(f"Build check failed:\n- {str(exc).replace(chr(10), chr(10) + '- ')}")
        return 1
    if errors:
        print("Build check failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"Build check passed: generated_files={len(_load_generated_entries(root))}")
    return 0
