#!/usr/bin/env python3
"""Build Proof Engine MASTER (v1.5).

Concatenates markdown modules in `skills/proof_engine/modules/` in lexical order
(excluding files starting with '99_').

Usage:
  python tools/build_proof_engine_v1_5.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = ROOT / "skills" / "proof_engine" / "modules"
OUT = ROOT / "skills" / "proof_engine" / "MASTER_v1.5.md"


def main():
    pattern = re.compile(r"^\d{2}_.+\.md$")
    modules = [p for p in MODULES_DIR.iterdir() if p.is_file() and pattern.match(p.name) and not p.name.startswith("99_")]
    modules = sorted(modules, key=lambda p: p.name)
    if not modules:
        raise SystemExit("No modules found in skills/proof_engine/modules")

    parts = ["# MASTER v1.5 (Proof Engine)\n\n"]
    parts.append("> This file is generated by `tools/build_proof_engine_v1_5.py`.  \n")
    parts.append("> **Normative rules:** `boot/04_MODE_LOCK_FORMAT_v1.3.2.md` + `boot/11_COMPLETION_FIRST_ANTI_SHORTCUT_v1.5.md` + `boot/13_SCIENTIFIC_ASSISTANT_OUTPUT_DISCIPLINE_v1.5.md` + `skills/research_core/S240_pessimistic_proof_verification.md` + `skills/research_core/S241_progressive_proof_verification.md`.\n\n---\n")
    for p in modules:
        parts.append(p.read_text(encoding="utf-8").rstrip())
        parts.append("\n\n---\n")
    OUT.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
