#!/usr/bin/env python3
"""Build Coding Engine MASTER (v1.3.2).

Same as v1.2 but updated normative rule references (LOCKED guard v1.3).

Usage:
  python tools/build_coding_engine_v1_3.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = ROOT / "skills" / "coding_engine" / "modules"
OUT = ROOT / "skills" / "coding_engine" / "MASTER_v1.3.2.md"

def main():
    pattern = re.compile(r"^\d{2}_.+\.md$")
    modules = [p for p in MODULES_DIR.iterdir() if p.is_file() and pattern.match(p.name) and not p.name.startswith("99_")]
    modules = sorted(modules, key=lambda p: p.name)
    if not modules:
        raise SystemExit("No modules found in skills/coding_engine/modules")

    parts = ["# MASTER v1.3.2 (Coding Engine)\n\n"]
    parts.append("> This file is generated by `tools/build_coding_engine_v1_3.py`.  \n")
    parts.append("> **Normative rules:** `skills/reproducibility/S430_debug_vibe_core.md` + `boot/10_LOCKED_SCOPE_GUARD_v1.3.md`.\n\n---\n")
    for p in modules:
        parts.append(p.read_text(encoding="utf-8").rstrip())
        parts.append("\n\n---\n")
    OUT.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")

if __name__ == "__main__":
    main()
