#!/usr/bin/env python3
"""Build a human-readable navigation index.

- Scans skills/**/S*.md
- Groups by category from YAML front matter
- Writes INDEX.md at repo root
"""

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
MANIFEST = ROOT / "skills_manifest.yaml"
OUT = ROOT / "INDEX.md"

FRONT_MATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)

def parse_front_matter(text: str):
    m = FRONT_MATTER_RE.match(text)
    if not m:
        return None
    return yaml.safe_load(m.group(1))

def get_version() -> str:
    if MANIFEST.exists():
        try:
            data = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
            v = str(data.get("version", "")).strip()
            if v:
                return v
        except Exception:
            pass
    return "v1.3.2"

def main():
    buckets = {}
    for p in sorted(SKILLS_DIR.glob("**/S*.md")):
        text = p.read_text(encoding="utf-8")
        fm = parse_front_matter(text) or {}
        cat = fm.get("category", "uncategorized")
        sid = fm.get("id", p.stem)
        name = fm.get("name", p.stem)
        buckets.setdefault(cat, []).append((sid, name, p.relative_to(ROOT).as_posix()))

    version = get_version()
    lines = [f"# Index ({version})\n", "This file is generated by `tools/build_index.py`.\n"]
    for cat in sorted(buckets.keys()):
        lines.append(f"## {cat}\n")
        for sid, name, rel in buckets[cat]:
            lines.append(f"- **{sid}** `{name}` — {rel}")
        lines.append("")

    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")

if __name__ == "__main__":
    main()
