#!/usr/bin/env python3
"""Build a human-readable navigation index.

- Scans real skill files `skills/**/S###_*.md`
- Groups by category from YAML front matter
- Writes INDEX.md at repo root
"""

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
MANIFEST = ROOT / "skills_manifest.yaml"
OUT = ROOT / "INDEX.md"

FRONT_MATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)
SKILL_FILENAME_RE = re.compile(r"^S\d+_.*\.md$")

def parse_front_matter(text: str):
    m = FRONT_MATTER_RE.match(text)
    if not m:
        return None
    return yaml.safe_load(m.group(1))

def iter_skill_files():
    for p in sorted(SKILLS_DIR.rglob("*.md")):
        rel = p.relative_to(SKILLS_DIR).as_posix()
        if "platform_zyr_skills/rewrites/" in rel:
            continue
        if SKILL_FILENAME_RE.match(p.name):
            yield p


def load_manifest_composites():
    if not MANIFEST.exists():
        return []
    data = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
    entries = []
    for item in data.get("skills", []) or []:
        if str(item.get("category", "")).strip() != "composite":
            continue
        sid = str(item.get("id", "")).strip()
        name = str(item.get("name", sid)).strip()
        rel = str(item.get("path", "")).strip()
        if sid and rel:
            entries.append((sid, name, rel))
    return entries

def get_version() -> str:
    if MANIFEST.exists():
        try:
            data = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
            v = str(data.get("version", "")).strip()
            if v:
                return v
        except Exception:
            pass
    return "v1.3.2"

def main():
    buckets = {}
    for p in iter_skill_files():
        text = p.read_text(encoding="utf-8")
        fm = parse_front_matter(text) or {}
        cat = fm.get("category", "uncategorized")
        sid = fm.get("id", p.stem)
        name = fm.get("name", p.stem)
        buckets.setdefault(cat, []).append((sid, name, p.relative_to(ROOT).as_posix()))

    for sid, name, rel in load_manifest_composites():
        buckets.setdefault("composite", []).append((sid, name, rel))

    version = get_version()
    lines = [f"# Index ({version})\n", "This file is generated by `tools/build_index.py`.\n"]
    for cat in sorted(buckets.keys()):
        lines.append(f"## {cat}\n")
        for sid, name, rel in buckets[cat]:
            lines.append(f"- **{sid}** `{name}` — {rel}")
        lines.append("")

    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")

if __name__ == "__main__":
    main()
